// Code generated by counterfeiter. DO NOT EDIT.
package credhubfakes

import (
	"net/http"
	"net/url"
	"sync"
)

type FakeCredhubRequestor struct {
	RequestStub        func(method string, pathStr string, query url.Values, body interface{}, checkServerErr bool) (*http.Response, error)
	requestMutex       sync.RWMutex
	requestArgsForCall []struct {
		method         string
		pathStr        string
		query          url.Values
		body           interface{}
		checkServerErr bool
	}
	requestReturns struct {
		result1 *http.Response
		result2 error
	}
	requestReturnsOnCall map[int]struct {
		result1 *http.Response
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCredhubRequestor) Request(method string, pathStr string, query url.Values, body interface{}, checkServerErr bool) (*http.Response, error) {
	fake.requestMutex.Lock()
	ret, specificReturn := fake.requestReturnsOnCall[len(fake.requestArgsForCall)]
	fake.requestArgsForCall = append(fake.requestArgsForCall, struct {
		method         string
		pathStr        string
		query          url.Values
		body           interface{}
		checkServerErr bool
	}{method, pathStr, query, body, checkServerErr})
	fake.recordInvocation("Request", []interface{}{method, pathStr, query, body, checkServerErr})
	fake.requestMutex.Unlock()
	if fake.RequestStub != nil {
		return fake.RequestStub(method, pathStr, query, body, checkServerErr)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.requestReturns.result1, fake.requestReturns.result2
}

func (fake *FakeCredhubRequestor) RequestCallCount() int {
	fake.requestMutex.RLock()
	defer fake.requestMutex.RUnlock()
	return len(fake.requestArgsForCall)
}

func (fake *FakeCredhubRequestor) RequestArgsForCall(i int) (string, string, url.Values, interface{}, bool) {
	fake.requestMutex.RLock()
	defer fake.requestMutex.RUnlock()
	return fake.requestArgsForCall[i].method, fake.requestArgsForCall[i].pathStr, fake.requestArgsForCall[i].query, fake.requestArgsForCall[i].body, fake.requestArgsForCall[i].checkServerErr
}

func (fake *FakeCredhubRequestor) RequestReturns(result1 *http.Response, result2 error) {
	fake.RequestStub = nil
	fake.requestReturns = struct {
		result1 *http.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeCredhubRequestor) RequestReturnsOnCall(i int, result1 *http.Response, result2 error) {
	fake.RequestStub = nil
	if fake.requestReturnsOnCall == nil {
		fake.requestReturnsOnCall = make(map[int]struct {
			result1 *http.Response
			result2 error
		})
	}
	fake.requestReturnsOnCall[i] = struct {
		result1 *http.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeCredhubRequestor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.requestMutex.RLock()
	defer fake.requestMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCredhubRequestor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
