// Code generated by counterfeiter. DO NOT EDIT.
package filefakes

import (
	"io"
	"sync"

	"github.com/pivotal-cf/aqueduct-courier/file"
)

type FakeData struct {
	NameStub        func() string
	nameMutex       sync.RWMutex
	nameArgsForCall []struct{}
	nameReturns     struct {
		result1 string
	}
	nameReturnsOnCall map[int]struct {
		result1 string
	}
	ContentStub        func() io.Reader
	contentMutex       sync.RWMutex
	contentArgsForCall []struct{}
	contentReturns     struct {
		result1 io.Reader
	}
	contentReturnsOnCall map[int]struct {
		result1 io.Reader
	}
	MimeTypeStub        func() string
	mimeTypeMutex       sync.RWMutex
	mimeTypeArgsForCall []struct{}
	mimeTypeReturns     struct {
		result1 string
	}
	mimeTypeReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeData) Name() string {
	fake.nameMutex.Lock()
	ret, specificReturn := fake.nameReturnsOnCall[len(fake.nameArgsForCall)]
	fake.nameArgsForCall = append(fake.nameArgsForCall, struct{}{})
	fake.recordInvocation("Name", []interface{}{})
	fake.nameMutex.Unlock()
	if fake.NameStub != nil {
		return fake.NameStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.nameReturns.result1
}

func (fake *FakeData) NameCallCount() int {
	fake.nameMutex.RLock()
	defer fake.nameMutex.RUnlock()
	return len(fake.nameArgsForCall)
}

func (fake *FakeData) NameReturns(result1 string) {
	fake.NameStub = nil
	fake.nameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeData) NameReturnsOnCall(i int, result1 string) {
	fake.NameStub = nil
	if fake.nameReturnsOnCall == nil {
		fake.nameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.nameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeData) Content() io.Reader {
	fake.contentMutex.Lock()
	ret, specificReturn := fake.contentReturnsOnCall[len(fake.contentArgsForCall)]
	fake.contentArgsForCall = append(fake.contentArgsForCall, struct{}{})
	fake.recordInvocation("Content", []interface{}{})
	fake.contentMutex.Unlock()
	if fake.ContentStub != nil {
		return fake.ContentStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.contentReturns.result1
}

func (fake *FakeData) ContentCallCount() int {
	fake.contentMutex.RLock()
	defer fake.contentMutex.RUnlock()
	return len(fake.contentArgsForCall)
}

func (fake *FakeData) ContentReturns(result1 io.Reader) {
	fake.ContentStub = nil
	fake.contentReturns = struct {
		result1 io.Reader
	}{result1}
}

func (fake *FakeData) ContentReturnsOnCall(i int, result1 io.Reader) {
	fake.ContentStub = nil
	if fake.contentReturnsOnCall == nil {
		fake.contentReturnsOnCall = make(map[int]struct {
			result1 io.Reader
		})
	}
	fake.contentReturnsOnCall[i] = struct {
		result1 io.Reader
	}{result1}
}

func (fake *FakeData) MimeType() string {
	fake.mimeTypeMutex.Lock()
	ret, specificReturn := fake.mimeTypeReturnsOnCall[len(fake.mimeTypeArgsForCall)]
	fake.mimeTypeArgsForCall = append(fake.mimeTypeArgsForCall, struct{}{})
	fake.recordInvocation("MimeType", []interface{}{})
	fake.mimeTypeMutex.Unlock()
	if fake.MimeTypeStub != nil {
		return fake.MimeTypeStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.mimeTypeReturns.result1
}

func (fake *FakeData) MimeTypeCallCount() int {
	fake.mimeTypeMutex.RLock()
	defer fake.mimeTypeMutex.RUnlock()
	return len(fake.mimeTypeArgsForCall)
}

func (fake *FakeData) MimeTypeReturns(result1 string) {
	fake.MimeTypeStub = nil
	fake.mimeTypeReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeData) MimeTypeReturnsOnCall(i int, result1 string) {
	fake.MimeTypeStub = nil
	if fake.mimeTypeReturnsOnCall == nil {
		fake.mimeTypeReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.mimeTypeReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeData) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.nameMutex.RLock()
	defer fake.nameMutex.RUnlock()
	fake.contentMutex.RLock()
	defer fake.contentMutex.RUnlock()
	fake.mimeTypeMutex.RLock()
	defer fake.mimeTypeMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeData) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ file.Data = new(FakeData)
