---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/library/golang
    tag: 1.21.5

inputs:
- name: aqueduct-courier
  path: go/src/github.com/pivotal-cf/aqueduct-courier
- name: version
- name: ci

outputs:
- name: binary-tar
- name: binaries

run:
  path: ci/ci/tasks/build-binaries

params:
  DATA_LOADER_URL:
  ENSURE_HTTPS:
