#!/usr/bin/env bash

set -euo pipefail

GOPATH=${PWD}/go
GOARCH=amd64

go version

VERSION=$(cat version/version)
pushd "$PWD/go/src/github.com/pivotal-cf/aqueduct-courier"
    VERSION="$VERSION.$(git rev-parse --short HEAD)"
popd

VERSION_FLAG="-X=github.com/pivotal-cf/aqueduct-courier/cmd.version=$VERSION"
DATA_LOADER_FLAG="-X=github.com/pivotal-cf/aqueduct-courier/cmd.dataLoaderURL=$DATA_LOADER_URL"
GO_FLAGS="-ldflags $VERSION_FLAG $DATA_LOADER_FLAG"

go build -o "aqueduct-linux-$GOARCH" $GO_FLAGS github.com/pivotal-cf/aqueduct-courier
GOOS=darwin go build -o "aqueduct-darwin-$GOARCH" $GO_FLAGS github.com/pivotal-cf/aqueduct-courier
GOOS=windows go build -o "aqueduct-windows-$GOARCH.exe" $GO_FLAGS github.com/pivotal-cf/aqueduct-courier

tar czvf aqueduct-binaries/aqueduct-cli.tgz \
    "aqueduct-linux-$GOARCH" \
    "aqueduct-darwin-$GOARCH" \
    "aqueduct-windows-$GOARCH.exe"
