---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: tpi-docker-virtual.usw1.packages.broadcom.com/library/golang
    tag: 1.21.10
    username: ((jfrog-artifactory.jfrog-username))
    password: ((jfrog-artifactory.jfrog-password))

inputs:
- name: aqueduct-courier
  path: go/src/github.com/pivotal-cf/aqueduct-courier
- name: version
- name: ci

outputs:
- name: binary-tar
- name: binaries

run:
  path: ci/ci/tasks/build-binaries

params:
  DATA_LOADER_URL:
  ENSURE_HTTPS:
