#!/usr/bin/env bash

set -xeou pipefail

tar xvf binaries/*.tgz

./aqueduct-linux-amd64 --version

./aqueduct-linux-amd64 collect --env-type development --output-dir . --insecure-skip-tls-verify

./aqueduct-linux-amd64 send --path *.tar
