#!/usr/bin/env bash

set -euo pipefail

GOPATH=${PWD}/go
PATH=${GOPATH}/bin:${PATH}

go version
go env -w GO111MODULE=auto

go install github.com/onsi/ginkgo/ginkgo@latest

pushd go/src/github.com/pivotal-cf/aqueduct-courier
  ginkgo -failOnPending -race -randomizeAllSpecs -randomizeSuites -r .
popd
