#!/usr/bin/env bash

set -euo pipefail

GOPATH=${PWD}/go
PATH=${GOPATH}/bin:${PATH}

go get github.com/onsi/ginkgo/ginkgo

ginkgo -failOnPending -race -randomizeAllSpecs -r -nodes=4 go/src/github.com/pivotal-cf/aqueduct-courier
