---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: tpi-docker-virtual.usw1.packages.broadcom.com/library/ubuntu
    tag: jammy
    username: ((jfrog-artifactory.jfrog-username))
    password: ((jfrog-artifactory.jfrog-password))

inputs:
- name: version
- name: aqueduct-courier
- name: binaries-tar
- name: ci

outputs:
- name: release-files

run:
  path: sh
  args:
  - -c
  - |
    #!/bin/bash

    set -xe

    mkdir tmp-release-files

    tar -xvf binaries-tar/*.tgz -C tmp-release-files

    VERSION=$(cat version/version)
    cp ci/ci/tasks/collect.yml tmp-release-files
    cp ci/ci/tasks/send.yml tmp-release-files

    tar -C tmp-release-files -zcf release-files/telemetry-collector-"$VERSION".tgz .
