---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: dev.registry.pivotal.io/tanzu-portfolio-insights/telemetry-for-vms/base-ci-image
    username: ((pivotal-image-registry.registry-username))
    password: ((pivotal-image-registry.registry-password))
    tag: latest

inputs:
  - name: aqueduct-courier
  - name: ci

run:
  path: ci/ci/tasks/scan-repo.sh
