---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: tpi-docker-virtual.usw1.packages.broadcom.com/tanzu-portfolio-insights/telemetry-for-vms/base-ci-image
    username: ((jfrog-artifactory.jfrog-username))
    password: ((jfrog-artifactory.jfrog-password))
    tag: latest

inputs:
  - name: aqueduct-courier
  - name: ci

run:
  path: ci/ci/tasks/scan-repo.sh
