---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/library/golang
    tag: 1.21.4

inputs:
- name: ci
- name: aqueduct-courier
  path: go/src/github.com/pivotal-cf/aqueduct-courier

outputs:
- name: aqueduct-courier
  path: go/src/github.com/pivotal-cf/aqueduct-courier

run:
  path: ci/ci/tasks/update-utils

params:
  GITHUB_NAME:
  GITHUB_EMAIL:
  GITHUB_ACCESS_TOKEN:
