// Code generated by counterfeiter. DO NOT EDIT.
package operationsfakes

import (
	"sync"

	"github.com/pivotal-cf/aqueduct-courier/coreconsumption"
)

type FakeCoreConsumptionDataCollector struct {
	CollectStub        func() ([]coreconsumption.Data, error)
	collectMutex       sync.RWMutex
	collectArgsForCall []struct {
	}
	collectReturns struct {
		result1 []coreconsumption.Data
		result2 error
	}
	collectReturnsOnCall map[int]struct {
		result1 []coreconsumption.Data
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCoreConsumptionDataCollector) Collect() ([]coreconsumption.Data, error) {
	fake.collectMutex.Lock()
	ret, specificReturn := fake.collectReturnsOnCall[len(fake.collectArgsForCall)]
	fake.collectArgsForCall = append(fake.collectArgsForCall, struct {
	}{})
	stub := fake.CollectStub
	fakeReturns := fake.collectReturns
	fake.recordInvocation("Collect", []interface{}{})
	fake.collectMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCoreConsumptionDataCollector) CollectCallCount() int {
	fake.collectMutex.RLock()
	defer fake.collectMutex.RUnlock()
	return len(fake.collectArgsForCall)
}

func (fake *FakeCoreConsumptionDataCollector) CollectCalls(stub func() ([]coreconsumption.Data, error)) {
	fake.collectMutex.Lock()
	defer fake.collectMutex.Unlock()
	fake.CollectStub = stub
}

func (fake *FakeCoreConsumptionDataCollector) CollectReturns(result1 []coreconsumption.Data, result2 error) {
	fake.collectMutex.Lock()
	defer fake.collectMutex.Unlock()
	fake.CollectStub = nil
	fake.collectReturns = struct {
		result1 []coreconsumption.Data
		result2 error
	}{result1, result2}
}

func (fake *FakeCoreConsumptionDataCollector) CollectReturnsOnCall(i int, result1 []coreconsumption.Data, result2 error) {
	fake.collectMutex.Lock()
	defer fake.collectMutex.Unlock()
	fake.CollectStub = nil
	if fake.collectReturnsOnCall == nil {
		fake.collectReturnsOnCall = make(map[int]struct {
			result1 []coreconsumption.Data
			result2 error
		})
	}
	fake.collectReturnsOnCall[i] = struct {
		result1 []coreconsumption.Data
		result2 error
	}{result1, result2}
}

func (fake *FakeCoreConsumptionDataCollector) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.collectMutex.RLock()
	defer fake.collectMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCoreConsumptionDataCollector) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
