---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/library/ubuntu
    tag: xenial

inputs:
- name: version
- name: aqueduct-courier
- name: binaries-tar
- name: ci

outputs:
- name: release-files

run:
  path: sh
  args:
  - -c
  - |
    #!/bin/bash

    set -xe

    tar -xvf binaries-tar/*.tgz -C release-files

    VERSION=$(cat version/version)
    cp ci/ci/tasks/collect.yml release-files/concourse-collect-task-$VERSION.yml
    cp ci/ci/tasks/send.yml release-files/concourse-send-task-$VERSION.yml
