// Code generated by counterfeiter. DO NOT EDIT.
package opsfakes

import (
	"sync"
)

type FakeTarReader struct {
	ReadFileStub        func(string) ([]byte, error)
	readFileMutex       sync.RWMutex
	readFileArgsForCall []struct {
		arg1 string
	}
	readFileReturns struct {
		result1 []byte
		result2 error
	}
	readFileReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	TarFilePathStub        func() string
	tarFilePathMutex       sync.RWMutex
	tarFilePathArgsForCall []struct{}
	tarFilePathReturns     struct {
		result1 string
	}
	tarFilePathReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTarReader) ReadFile(arg1 string) ([]byte, error) {
	fake.readFileMutex.Lock()
	ret, specificReturn := fake.readFileReturnsOnCall[len(fake.readFileArgsForCall)]
	fake.readFileArgsForCall = append(fake.readFileArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("ReadFile", []interface{}{arg1})
	fake.readFileMutex.Unlock()
	if fake.ReadFileStub != nil {
		return fake.ReadFileStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.readFileReturns.result1, fake.readFileReturns.result2
}

func (fake *FakeTarReader) ReadFileCallCount() int {
	fake.readFileMutex.RLock()
	defer fake.readFileMutex.RUnlock()
	return len(fake.readFileArgsForCall)
}

func (fake *FakeTarReader) ReadFileArgsForCall(i int) string {
	fake.readFileMutex.RLock()
	defer fake.readFileMutex.RUnlock()
	return fake.readFileArgsForCall[i].arg1
}

func (fake *FakeTarReader) ReadFileReturns(result1 []byte, result2 error) {
	fake.ReadFileStub = nil
	fake.readFileReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeTarReader) ReadFileReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.ReadFileStub = nil
	if fake.readFileReturnsOnCall == nil {
		fake.readFileReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.readFileReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeTarReader) TarFilePath() string {
	fake.tarFilePathMutex.Lock()
	ret, specificReturn := fake.tarFilePathReturnsOnCall[len(fake.tarFilePathArgsForCall)]
	fake.tarFilePathArgsForCall = append(fake.tarFilePathArgsForCall, struct{}{})
	fake.recordInvocation("TarFilePath", []interface{}{})
	fake.tarFilePathMutex.Unlock()
	if fake.TarFilePathStub != nil {
		return fake.TarFilePathStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.tarFilePathReturns.result1
}

func (fake *FakeTarReader) TarFilePathCallCount() int {
	fake.tarFilePathMutex.RLock()
	defer fake.tarFilePathMutex.RUnlock()
	return len(fake.tarFilePathArgsForCall)
}

func (fake *FakeTarReader) TarFilePathReturns(result1 string) {
	fake.TarFilePathStub = nil
	fake.tarFilePathReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeTarReader) TarFilePathReturnsOnCall(i int, result1 string) {
	fake.TarFilePathStub = nil
	if fake.tarFilePathReturnsOnCall == nil {
		fake.tarFilePathReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.tarFilePathReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeTarReader) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.readFileMutex.RLock()
	defer fake.readFileMutex.RUnlock()
	fake.tarFilePathMutex.RLock()
	defer fake.tarFilePathMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTarReader) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
