resource_types:
- name: bbl-state-resource
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/cfinfrastructure/bbl-state-resource
    tag: latest
- name: bosh-deployment
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/cloudfoundry/bosh-deployment-resource

resources:
- name: bbl-state
  type: bbl-state-resource
  source:
    bucket: windows-worker-bbl-state
    iaas: gcp
    gcp_region: us-east1
    gcp_service_account_key: {{courier-gcp-service-account-key}}
- name: manifest
  type: git
  source:
    branch: main
    uri: git@github.com:pivotal-cf/aqueduct-courier
    private_key: {{courier-git-deploy-private-key}}
    paths:
    - ci/manifest/windows-worker.yml
- name: windows-worker
  type: bosh-deployment
  source:
    deployment: windows-worker
    skip_check: true
- name: windows-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-windows2016-go_agent

jobs:
- name: bbl-up
  plan:
  - get: bbl-state
  - put: bbl-state
    params:
      command: up
      state_dir: bbl-state
- name: deploy-windows-worker
  plan:
  - in_parallel:
    - get: bbl-state
      passed: [bbl-up]
      trigger: true
    - get: windows-stemcell
    - get: manifest
      trigger: true
  - put: windows-worker
    params:
      manifest: manifest/ci/manifest/windows-worker.yml
      source_file: bbl-state/bdr-source-file
      vars:
        team: telemetry-and-insights
        tsa_host: {{tsa_host}}
        tsa_host_public_key: {{tsa_host_public_key}}
        worker_private_key: {{windows_worker_private_key}}
      stemcells:
      - windows-stemcell/*.tgz
